Update hyde-themes.db
HyDE-Project/hyde-gallery pull request #7
Opened 2024-05-09 13:53 UTC by tryprncp

Added themes: AI Arts, Abstract, E-girls, Cars

2024-05-09 14:50 UTC, kRHYME7 commented
Cool! 

Can you please add some preview?

Just add it on each Theme directory

2024-05-09 15:09 UTC, kRHYME7 requested changes
Lets' discuss each theme per PR. 

I think I can help you with some changes

2024-05-09 15:09 UTC, kRHYME7 commented on hyde-themes.db
> +[E-girls]
![image](https://github.com/kRHYME7/hyde-gallery/assets/53417443/e3dc8e45-67cd-47c4-885e-2171ec2a85fe)

Colors do not fit the theme i guess we need to get some Ideas on other Themes.

2024-05-09 15:09 UTC, kRHYME7 commented on hyde-themes.db
> +[Abstract]
https://github.com/kRHYME7/hyde-gallery/blob/hyde-gallery/Windows%2011/Windows%252011.png

You can use the Windows 11 theme for this I guess should look better 

Here's the repo
https://github.com/kRHYME7/hyde-gallery/tree/Windows-11

2024-10-14 06:23 UTC, rubiin commented
Any updates on this. I will take charge of this in new PR . Seems to be stuck for some time now

2024-10-14 06:33 UTC, kRHYME7 commented
I guess it's fine. You can do 1 theme per pr

2025-07-28 04:27 UTC, sudeepbatra commented
Lets go some more themes please. In need of some great light themes as well

2025-08-14 18:47 UTC, boulder-roller commented
@kRHYME7 can we close this as not planned pls

2025-12-28 08:24 UTC, closed without merging